
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:413472068967:android:83eec4cb2c563ec838cbc2",
      firebase_cli_token:"1//03XW25QNy8koNCgYIARAAGAMSNwF-L9IrE11UihA4EdRukKBq0qJZtNgl_Saph3sVFUmmNgkGwEyzvjURb1045AKOLlMS50QU9fo",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohammedgamal.rc@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
