
default_platform(:android)
platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart"
    firebase_app_distribution(
      app: "1:413472068967:android:83eec4cb2c563ec838cbc2",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohammedgamal.rc@gmail.com",
      release_notes: "Test Github Action Firebase Distribution"
    )
  end
end
