
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:391819994416:android:29052bb6d7acdd518514f5",
      firebase_cli_token:"1//03LakIuFXMv54CgYIARAAGAMSNwF-L9IrLX-YZHZSJiSsGBp1F7KsZOt9TNF7L8INrDtwIFEFCLYOkNgYYotl0VrmcV4dAQOwxhE",
      # android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohammedgamal.rc@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
